data:
  raw_path: "data/raw/creditcard.csv"


models:
  decision_tree:
    type: "DecisionTreeClassifier"
    params:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 10,
      class_weight: "balanced"
      random_state: 42

  random_forest:
    type: "RandomForestClassifier"
    params:
      n_estimators: 200
      max_depth: "None"
      class_weight: "balanced"
      random_state: 42

  xgboost:
    type: "XGBClassifier"
    params:
      n_estimators: 400
      max_depth: 6
      learning_rate: 0.05
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
